# Generated by Django 5.2.11 on 2026-02-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_attendancelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attended_classes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='total_classes',
        ),
    ]
