# Generated by Django 5.2.11 on 2026-02-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_remove_attendance_attended_classes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='last_updated',
        ),
    ]
