# Generated by Django 5.2.11 on 2026-02-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_badge_competition_competitionparticipant_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='category',
            field=models.CharField(choices=[('internal', 'Internal Contest'), ('external', 'External Opportunity')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='competition',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
