# Generated by Django 5.2.11 on 2026-02-21 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_competition_category_competition_external_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='mode_type',
            field=models.CharField(choices=[('quiz', 'Quiz Mode'), ('coding', 'Coding Mode'), ('english', 'English Mode'), ('memory', 'Memory Mode')], default='quiz', max_length=20),
        ),
        migrations.AddField(
            model_name='competition',
            name='time_limit',
            field=models.IntegerField(default=15, help_text='Time limit in minutes'),
        ),
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('xp_value', models.IntegerField(default=10)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='lms.competition')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('fill_blank', 'Fill in the Blanks'), ('rearrange', 'Rearrange Sentence'), ('match', 'Vocabulary Match')], max_length=20)),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('options_json', models.JSONField(blank=True, help_text='Use for matching pairs or MCQ options', null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_questions', to='lms.competition')),
            ],
        ),
        migrations.CreateModel(
            name='MemorySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_list', models.JSONField(help_text='List of words to remember')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_sets', to='lms.competition')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('memory_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.memoryset')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='lms.competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'competition')},
            },
        ),
    ]
