# Generated by Django 5.2.11 on 2026-02-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_competition_mode_type_competition_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
