# Generated by Django 5.2.11 on 2026-02-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_teachercourseassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionattempt',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
