# Generated by Django 5.2.11 on 2026-02-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_competitionattempt_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_classes_completed',
            field=models.IntegerField(default=0, help_text='Number of classes completed for this course so far'),
        ),
    ]
