# Generated by Django 5.2.11 on 2026-02-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_dailyattendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='manual_progress',
            field=models.IntegerField(default=0, help_text='Manually entered progress percentage (0-100)'),
        ),
    ]
