# Generated by Django 5.2.10 on 2026-02-25 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_enrollment_manual_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('allow_audio', models.BooleanField(default=True)),
                ('allow_text', models.BooleanField(default=True)),
                ('allow_file', models.BooleanField(default=True)),
                ('reward_xp', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='lms.course')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, null=True)),
                ('audio_response', models.FileField(blank=True, null=True, upload_to='submissions/audio/')),
                ('file_response', models.FileField(blank=True, null=True, upload_to='submissions/files/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('correction', 'Needs Improvement')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.dailychallenge')),
            ],
            options={
                'unique_together': {('challenge', 'student')},
            },
        ),
    ]
