# Generated by Django 5.2.10 on 2026-02-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_dailychallenge_challengesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='quiz_score',
            field=models.IntegerField(default=0, help_text='Number of correct answers if type is quiz'),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='total_quiz_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='challenge_type',
            field=models.CharField(choices=[('mission', 'Mission (Text/Audio/File)'), ('quiz', 'Quiz Contest')], default='mission', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyChallengeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='lms.dailychallenge')),
            ],
        ),
    ]
