# Generated by Django 5.1.7 on 2026-02-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_challengesubmission_quiz_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_progress',
            field=models.IntegerField(default=0, help_text='Global progress percentage for this course (0-100)'),
        ),
    ]
