# Generated by Django 5.2.11 on 2026-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_course_course_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendancelog',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], db_index=True, default='present', max_length=10),
        ),
    ]
