# Generated by Django 5.1.7 on 2026-04-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_dailyattendancelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='lms.course'),
        ),
    ]
