# Generated by Django 5.1.7 on 2026-04-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_competition_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyattendancelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyattendancelog',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_logs', to='lms.course'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendancelog',
            unique_together={('student', 'course', 'date')},
        ),
    ]
